/**
 * plugins/withIosVoIP.js
 *
 * Expo config plugin for iOS VoIP incoming calls (PushKit + CallKit).
 *
 * What this plugin does on every `expo prebuild`:
 *   1. Info.plist — adds UIBackgroundModes: voip, audio, fetch, remote-notification
 *   2. Info.plist — adds NSMicrophoneUsageDescription, NSCameraUsageDescription
 *   3. Entitlements — adds com.apple.developer.pushkit.voip: true
 *   4. Entitlements — adds aps-environment: development|production
 *   5. Entitlements — adds com.apple.developer.pushnotification-triggering: true
 *   6. Copies GywVoIPPushDelegate.swift into the iOS project folder
 *   7. Patches AppDelegate.mm with the VoIP import + setup call
 *   8. Adds RNCallKeep + RNVoipPushNotification pod lines to the Podfile
 *
 * Usage in app.json / app.config.js:
 *   "plugins": [ "./plugins/withIosVoIP" ]
 *
 * Run after any change:
 *   npx expo prebuild --clean --platform ios
 */

const {
  withInfoPlist,
  withEntitlementsPlist,
  withDangerousMod,
} = require('@expo/config-plugins');
const path = require('path');
const fs   = require('fs');

// ── 1 & 2: Info.plist — background modes + usage strings ────────────────────

function withVoIPInfoPlist(config) {
  return withInfoPlist(config, (mod) => {
    const plist = mod.modResults;

    // Background modes (merge, never overwrite)
    const required = ['voip', 'audio', 'fetch', 'remote-notification'];
    const existing = Array.isArray(plist.UIBackgroundModes) ? plist.UIBackgroundModes : [];
    plist.UIBackgroundModes = Array.from(new Set([...existing, ...required]));

    // Usage strings — set only if not already provided
    if (!plist.NSMicrophoneUsageDescription) {
      plist.NSMicrophoneUsageDescription =
        '$(PRODUCT_NAME) needs microphone access for voice and video calls.';
    }
    if (!plist.NSCameraUsageDescription) {
      plist.NSCameraUsageDescription =
        '$(PRODUCT_NAME) needs camera access for video calls.';
    }

    return mod;
  });
}

// ── 3, 4, 5: Entitlements ────────────────────────────────────────────────────

function withVoIPEntitlements(config) {
  return withEntitlementsPlist(config, (mod) => {
    const ent = mod.modResults;

    // PushKit VoIP entitlement — required for PKPushRegistry(.voIP)
    ent['com.apple.developer.pushkit.voip'] = true;

    // APS environment — "development" for debug/TestFlight, "production" for App Store.
    // Expo EAS Build sets this automatically via the provisioning profile;
    // we default to "development" here so local builds work without a profile.
    if (!ent['aps-environment']) {
      ent['aps-environment'] = 'development';
    }

    // Required to trigger VoIP push from a Notification Service Extension or
    // from the app itself in iOS 17+ push-to-talk / scheduled deliveries.
    // Safe to include even if you don't use it — it is a no-op otherwise.
    ent['com.apple.developer.pushnotification-triggering'] = true;

    return mod;
  });
}

// ── 6 & 7: Copy Swift file + patch AppDelegate ───────────────────────────────

function withVoIPNativeFiles(config) {
  return withDangerousMod(config, [
    'ios',
    async (mod) => {
      const projectRoot = mod.modRequest.projectRoot;
      const iosRoot     = path.join(projectRoot, 'ios');

      // Resolve the generated app folder (e.g. ios/GYW/ or ios/CallRN/)
      const appFolderName = resolveAppFolder(iosRoot);
      if (!appFolderName) {
        console.warn('[withIosVoIP] ⚠️  Could not find iOS app folder — run expo prebuild first');
        return mod;
      }
      const appFolder = path.join(iosRoot, appFolderName);

      // ── Copy GywVoIPPushDelegate.swift ─────────────────────────────────────
      const srcSwift  = path.join(projectRoot, 'ios-native-src', 'GywVoIPPushDelegate.swift');
      const destSwift = path.join(appFolder, 'GywVoIPPushDelegate.swift');

      if (fs.existsSync(srcSwift)) {
        fs.copyFileSync(srcSwift, destSwift);
        console.log('[withIosVoIP] Copied GywVoIPPushDelegate.swift →', path.relative(projectRoot, destSwift));
      } else {
        console.warn('[withIosVoIP] ⚠️  ios-native-src/GywVoIPPushDelegate.swift not found');
      }

      // ── Ensure empty bridging header exists ───────────────────────────────
      // Xcode requires a bridging header when mixing Swift + ObjC.
      // Expo does not create one by default; we create an empty one if absent.
      const bridgingHeaderPath = path.join(appFolder, `${appFolderName}-Bridging-Header.h`);
      if (!fs.existsSync(bridgingHeaderPath)) {
        fs.writeFileSync(
          bridgingHeaderPath,
          `//\n// ${appFolderName}-Bridging-Header.h\n// Auto-generated by withIosVoIP plugin.\n// Swift classes are exposed via -Swift.h auto-generated headers.\n//\n`,
          'utf8'
        );
        console.log('[withIosVoIP] Created bridging header →', path.relative(projectRoot, bridgingHeaderPath));
      }

      // ── Patch AppDelegate.mm ───────────────────────────────────────────────
      const appDelegatePath = path.join(appFolder, 'AppDelegate.mm');
      if (!fs.existsSync(appDelegatePath)) {
        console.warn('[withIosVoIP] ⚠️  AppDelegate.mm not found at', appDelegatePath);
        return mod;
      }

      let src = fs.readFileSync(appDelegatePath, 'utf8');
      let changed = false;

      // Patch 1: import (insert after #import "AppDelegate.h")
      const importLine = '#import "GywVoIPPushDelegate-Swift.h"';
      if (!src.includes(importLine)) {
        src = src.replace(
          /#import "AppDelegate\.h"/,
          `#import "AppDelegate.h"\n${importLine}`
        );
        changed = true;
      }

      // Patch 2a: setup call after [super application:…] (Expo RCTAppDelegate style)
      const setupLine = '[[GywVoIPPushDelegate shared] setup];';
      if (!src.includes(setupLine)) {
        // Expo-generated AppDelegate.mm uses this pattern after [super …]
        const superPattern =
          /BOOL result = \[super application:application didFinishLaunchingWithOptions:launchOptions\];/;
        if (superPattern.test(src)) {
          src = src.replace(
            superPattern,
            `BOOL result = [super application:application didFinishLaunchingWithOptions:launchOptions];\n\n  // GYW VoIP — register PushKit (PKPushRegistry) + configure CallKit (CXProvider)\n  ${setupLine}`
          );
          changed = true;
        } else {
          // Fallback: insert before final `return YES`
          src = src.replace(
            /return YES;(\s*})(\s*@end)/,
            `\n  // GYW VoIP — register PushKit + configure CallKit\n  ${setupLine}\n  return YES;$1$2`
          );
          changed = true;
        }
      }

      if (changed) {
        fs.writeFileSync(appDelegatePath, src, 'utf8');
        console.log('[withIosVoIP] Patched AppDelegate.mm');
      } else {
        console.log('[withIosVoIP] AppDelegate.mm already patched — no changes needed');
      }

      return mod;
    },
  ]);
}

// ── 8: Podfile additions ──────────────────────────────────────────────────────
//
// react-native-callkeep and react-native-voip-push-notification are not
// auto-linked in Expo projects (they have no Expo plugin of their own).
// We inject the pod lines here so `pod install` picks them up.

function withVoIPPodfile(config) {
  return withDangerousMod(config, [
    'ios',
    async (mod) => {
      const podfilePath = path.join(mod.modRequest.projectRoot, 'ios', 'Podfile');
      if (!fs.existsSync(podfilePath)) {
        console.warn('[withIosVoIP] Podfile not found — run expo prebuild first');
        return mod;
      }

      let podfile = fs.readFileSync(podfilePath, 'utf8');

      // Pods to inject (idempotent — skip if already present)
      const pods = [
        { name: 'RNCallKeep',              path: '../node_modules/react-native-callkeep' },
        { name: 'RNVoipPushNotification',  path: '../node_modules/react-native-voip-push-notification' },
      ];

      let changed = false;
      for (const pod of pods) {
        const podLine = `  pod '${pod.name}', :path => '${pod.path}'`;
        if (!podfile.includes(`pod '${pod.name}'`)) {
          // Insert before `post_install` or before the final `end` of the target block
          const insertBefore = /(\s*post_install do)/;
          if (insertBefore.test(podfile)) {
            podfile = podfile.replace(insertBefore, `${podLine}\n$1`);
          } else {
            // Fallback: append inside target block
            podfile = podfile.replace(/(\nend\s*$)/, `\n${podLine}$1`);
          }
          changed = true;
          console.log(`[withIosVoIP] Podfile: added pod '${pod.name}'`);
        }
      }

      if (changed) {
        fs.writeFileSync(podfilePath, podfile, 'utf8');
      }

      return mod;
    },
  ]);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function resolveAppFolder(iosRoot) {
  if (!fs.existsSync(iosRoot)) return null;
  return (
    fs.readdirSync(iosRoot).find(
      (f) =>
        fs.statSync(path.join(iosRoot, f)).isDirectory() &&
        !f.startsWith('.') &&
        !f.endsWith('.xcodeproj') &&
        !f.endsWith('.xcworkspace') &&
        f !== 'Pods' &&
        f !== 'build'
    ) ?? null
  );
}

// ── Compose ───────────────────────────────────────────────────────────────────

module.exports = function withIosVoIP(config) {
  config = withVoIPInfoPlist(config);
  config = withVoIPEntitlements(config);
  config = withVoIPNativeFiles(config);
  config = withVoIPPodfile(config);
  return config;
};
